name: pipeline_main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Debug Information
      run: |
        echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"
        echo "Docker Password: ${{ secrets.DOCKER_PASSWORD }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd ./2_ano
        docker-compose -f docker-compose.yml build
